apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: Chechu <chechu@Chechus-MacBook-Pro-2.local>
    commit.image.appsody.dev/committer: Chechu <chechu@Chechus-MacBook-Pro-2.local>
    commit.image.appsody.dev/date: Wed Apr 22 21:47:31 2020 +0200
    commit.image.appsody.dev/message: script deployments add
    image.opencontainers.org/created: "2020-04-23T22:34:04+02:00"
    image.opencontainers.org/documentation: https://github.ibm.com/jesus-arteche/ocp-lab-backend
    image.opencontainers.org/revision: 1db796cd2e4ce98dbac618cf1f9b409c32fa5a1c-modified
    image.opencontainers.org/source: https://github.ibm.com/jesus-arteche/ocp-lab-backend/tree/master
    image.opencontainers.org/url: https://github.ibm.com/jesus-arteche/ocp-lab-backend
    stack.appsody.dev/authors: Chechu <chechuironman@gmail.com>
    stack.appsody.dev/configured: docker.io/chechuironman/python-stack:0.2.5
    stack.appsody.dev/created: "2020-04-23T22:22:56+02:00"
    stack.appsody.dev/description: Flask web Framework for Python with CORS enabled
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: b3e8a19b0a4b66a69daa8d1106f37bbe4167693a
    stack.appsody.dev/tag: dev.local/appsody/python-stack:0.2.5
    stack.appsody.dev/title: Python Flask
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: backend-ocp-lab
    stack.appsody.dev/id: python-stack
    stack.appsody.dev/version: 0.2.5
  name: k8smanager
  namespace: cloud-lab
spec:
  applicationImage: dev.local/backend-ocp-lab
  createKnativeService: false
  volumeMounts:
  - name: ssh-key
    mountPath: /project/userapp/libraries/ssh-key
    readOnly: true
  - name: kubeconfig
    mountPath: /project/userapp/libraries
    readOnly: true
  - mountPath: "/mnt/lab"
    name: cloud-lab-pvc
  - mountPath: /project/userapp/libraries
    name: host
  volumes:
    - name: host
      configMap:
        name: cloud-lab-ssh-host
    - name: cloud-lab-pvc
      persistentVolumeClaim:
        claimName: cloud-lab-pvc
    - name: ssh-key
      secret:
        secretName: ssh-key
    - name: kubeconfig
      secret:
        secretName: kubeconfig
  env:
  - name: MONGODB_USER
    valueFrom:
      secretKeyRef:
        key: database-user
        name: mongodb-cloud-lab
  - name: MONGODB_PASSWORD
    valueFrom:
      secretKeyRef:
        key: database-password
        name: mongodb-cloud-lab
  - name: MONGODB_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        key: database-admin-password
        name: mongodb-cloud-lab
  - name: MONGODB_DATABASE
    valueFrom:
      secretKeyRef:
        key: database-name
        name: mongodb-cloud-lab
  - name: MONGODB_HOST
    valueFrom:
      secretKeyRef:
        key: host
        name: mongodb-cloud-lab
  expose: false
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 60
  monitoring:
    labels:
      k8s-app: backend
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 8080
    type: ClusterIP
  stack: python-flask
  version: 1.0.0
status: {}