apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    image.opencontainers.org/created: "2020-01-01T21:07:35+01:00"
    stack.appsody.dev/configured: docker.io/appsody/python-flask:0.1
    stack.appsody.dev/created: 2019-11-14T10:29:19+0000
    stack.appsody.dev/revision: b3e8a19b0a4b66a69daa8d1106f37bbe4167693a
    stack.appsody.dev/tag: appsody/python-flask:0.1.6
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: backend
    stack.appsody.dev/version: 0.1.6
  name: backend
  namespace: cloud-lab
spec:
  env:
  - name: MONGODB_USER
    valueFrom:
      secretKeyRef:
        name: mongodb-cloud-lab
        key: database-user
  - name: MONGODB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mongodb-cloud-lab
        key: database-password
  - name: MONGODB_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mongodb-cloud-lab
        key: database-admin-password
  - name: MONGODB_DATABASE
    valueFrom:
      secretKeyRef:
        name: mongodb-cloud-lab
        key: database-name
  applicationImage: backend
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health
      port: 8081 
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    labels:
      k8s-app: backend
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 8081
    type: NodePort
  stack: python-flask
  version: 1.0.0
status: {}
