apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    image.opencontainers.org/created: "2020-04-23T23:10:54+02:00"
    stack.appsody.dev/authors: Chechu <chechuironman@gmail.com>
    stack.appsody.dev/configured: dev.local/appsody/python-stack:0.2.5
    stack.appsody.dev/created: "2020-04-23T22:22:56+02:00"
    stack.appsody.dev/description: Flask web Framework for Python with CORS enabled
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/tag: dev.local/appsody/python-stack:0.2.5
    stack.appsody.dev/title: Python Flask
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: python
    stack.appsody.dev/id: python-stack
    stack.appsody.dev/version: 0.2.5
  name: k8smanager
  namespace: cloud-lab
spec:
  applicationImage: dev.local/python
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    labels:
      k8s-app: python
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: python-stack
  version: 1.0.0
